name = "str33m-landing"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
route = "str33m.gg/*"

[build]
command = "npm run build"
watch_paths = ["src/**/*.{js,jsx,css}", "index.html"]